{% set name = "vbuild" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vbuild-{{ version }}.tar.gz
  sha256: b9ff9071fa61009563e935eddea4fdf1494c71941285f05fd57648f73dc19ecc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - poetry >=0.12
    - poetry-core
    - pip
  run:
    - python >=3.6
    - pscript >=0.7.0,<0.8.0

test:
  imports:
    - vbuild
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/manatlan/vbuild
  summary: A simple module to extract html/script/style from a vuejs '.vue' file (can minimize/es2015 compliant js) ... just py2 or py3, NO nodejs !
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rodja
